### ISSUE TITLE
No implementation found for method deactivateWifi on channel plugin_wifi_connect

### ISSUE THREAD

**Issue by gtuceturan** [CadisRaziel/plugin_wifi_connect#12]
when use activatewifi and deactivateWifi get error
No implementation found for method deactivateWifi on channel plugin_wifi_connect 

I use Android 11

**Comment by chenrilima** [comment]
we gonna check this, do you have some video or image? to help us

**Comment by gtuceturan** [comment]
![image](https://user-images.githubusercontent.com/59597081/176458611-628f7c41-ad15-4c5d-b024-50a06cbb73ea.png)


![image](https://user-images.githubusercontent.com/59597081/176458681-8357f586-5fc8-4e76-883e-7859813503ca.png)

**Comment by CadisRaziel** [comment]
let's check what's going on and we'll give you an answer @gtuceturan

**Comment by konnan900** [comment]
SwiftPluginWifiConnectPlugin.swift

line 31, missing the case value.

**Comment by chenrilima** [comment]
> 

can you show more details, about it?

**Comment by konnan900** [comment]
Sorry, I think I am answering wrongly. The reply is not related to the deactivateWifi.

but in /ios/Classes/SwiftPluginWifiConnectPlugin.swift line 31, really missing a case.

![image](https://user-images.githubusercontent.com/17021740/196207526-153ac358-aad9-4bac-a75d-0c9b79ac558e.png)

**Comment by chenrilima** [comment]
what you gonna try exactly?

**Comment by gtuceturan** [comment]
@CadisRaziel  @chenrilima did you fix ?
