### ISSUE TITLE
Does it have any way to force keep WiFI connected if no internet? 

### ISSUE THREAD

**Issue by elmar001** [CadisRaziel/plugin_wifi_connect#14]
Android 11, 12 makes it very hard for iOT devices. It is impossible to connect and configure them as Android detects that the connected WIFI  does not have internet connection. It would be handy to have something to keep it connected.

**Comment by chenrilima** [comment]
we gonna check this!
just wait for it.

**Comment by h1376h** [comment]
> Android 11, 12 makes it very hard for iOT devices. It is impossible to connect and configure them as Android detects that the connected WIFI does not have internet connection. It would be handy to have something to keep it connected.

The API you need for this purpose is probably [this](https://developer.android.com/guide/topics/connectivity/wifi-suggest). I'm not a kotlin developer, but am still working around best ways of adding it.

That API has so many limits, if the user tries to connect to another wifi (not the suggested ones by application/client), the client is blocked for 24 hours.

The other problem is "time". I don't know why and in theory I don't think there should be a delay when using that API in these situations, but in all my tests, this API is a bit slower than the other one and has some weird issues.

**Comment by elmar001** [comment]
Thanks, I tested with Android 10, 11 and 12. It works slower in Android 10 but works. In Android 11 and Android 12 it works and switches WiFi but it does not allow to use TCP Socket connection - IOT WiFi which does not have internet. Socket can not connect to IP port, seems like the problem is the OS detects that the WiFi does not have internet, it blocks all transport thru it. I reported the issue to Google but still no solution - https://issuetracker.google.com/issues/238443303

**Comment by h1376h** [comment]
> Thanks, I tested with Android 10, 11 and 12. It works slower in Android 10 but works. In Android 11 and Android 12 it works and switches WiFi but it does not allow to use TCP Socket connection - IOT WiFi which does not have internet. Socket can not connect to IP port, seems like the problem is the OS detects that the WiFi does not have internet, it blocks all transport thru it. I reported the issue to Google but still no solution - https://issuetracker.google.com/issues/238443303

You mentioned that you checked wifi IoT package with "withInternet: false" parameter (and with additional WiFiForIoTPlugin.forceWifiUsage(true)), have you tried it with "withInternet: true"?

And is there any reason for not using the WifiSuggestion API?

The implemtion of WifiSuggestion (the one that it calls when using internet: true) in the package you mentioned has some problems as well, I may have a better idea providing a dart code for you to test, if you could explain what are you expecting to happen.

Are you trying to make the phone auto-connect to a wifi?
Could the connection be peer to peer?
If not, did you test both of the available APIs? (WifiNetworkSpecifier and WifiSuggestion)

**Comment by elmar001** [comment]
> > Thanks, I tested with Android 10, 11 and 12. It works slower in Android 10 but works. In Android 11 and Android 12 it works and switches WiFi but it does not allow to use TCP Socket connection - IOT WiFi which does not have internet. Socket can not connect to IP port, seems like the problem is the OS detects that the WiFi does not have internet, it blocks all transport thru it. I reported the issue to Google but still no solution - https://issuetracker.google.com/issues/238443303
> 
> You mentioned that you checked wifi IoT package with "withInternet: false" parameter (and with additional WiFiForIoTPlugin.forceWifiUsage(true)), have you tried it with "withInternet: true"?
> 
> And is there any reason for not using the WifiSuggestion API?
> 
> The implemtion of WifiSuggestion (the one that it calls when using internet: true) in the package you mentioned has some problems as well, I may have a better idea providing a dart code for you to test, if you could explain what are you expecting to happen.
> 
> Are you trying to make the phone auto-connect to a wifi? Could the connection be peer to peer? If not, did you test both of the available APIs? (WifiNetworkSpecifier and WifiSuggestion)
Thanks for the response. 
1) Yes, I tried like "withInternet: true" as well. 

2) No special reason - I did not find any Flutter library implementing that one. Which pub.dev package implement that API? Or should I implement it myself?

3) It would be very helpful if you can help. This is all what I need: 

1) Joining to a WiFi with given SSID and password (Connected WiFi does not have internet and never will - It is a way similar to Bluetooth to connect, commission, configure device thru WiFi connection) 
2) Send byte data to that IOT device thru Flutter socket - something like: Socket.connect("ipHere", portNumberHere)

**Comment by h1376h** [comment]
```
package com.example.test

import android.content.Context
import android.net.wifi.WifiConfiguration
import android.net.wifi.WifiManager
import android.net.wifi.WifiNetworkSuggestion
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodCall //
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
    private val CHANNEL = "test/wifi"
    private var requestingPermission = false

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
            call,
            result ->
            when (call.method) {
                "initializeWifi" -> initializeWifi(call, result)
            }
        }
    }

    private fun initializeWifi(@NonNull call: MethodCall, result: MethodChannel.Result): Boolean {
        val wifiManager: WifiManager = context.getSystemService(Context.WIFI_SERVICE) as WifiManager
        val arguments: Map<String, String> = call.arguments()!!
        val ssid = arguments["ssid"]!!
        val password = arguments["password"]!!
        if (android.os.Build.VERSION.SDK_INT >= 29) {
            try {

                val wifiNetworkSuggestion: WifiNetworkSuggestion =
                    WifiNetworkSuggestion.Builder()
                        .setSsid(ssid.toString())
                        .setWpa2Passphrase(password.toString())
                        .build()
                val list: MutableList<WifiNetworkSuggestion> = ArrayList()
                list.add(wifiNetworkSuggestion)
                wifiManager.removeNetworkSuggestions(ArrayList<WifiNetworkSuggestion>())
                wifiManager.addNetworkSuggestions(list)
                result.success(true)
                return true
            } catch (e: Exception) {
                e.printStackTrace()
                result.success(false)
                return false
            }
        } else {
            try {
                var wifiConfiguration =
                    WifiConfiguration().apply {
                        SSID = "\"" + ssid + "\""
                        preSharedKey = "\"" + password + "\""
                        status = WifiConfiguration.Status.CURRENT // or nothing
                        allowedKeyManagement.set(WifiConfiguration.KeyMgmt.WPA_PSK)
                    }

                if (!wifiManager.isWifiEnabled) {
                    wifiManager.setWifiEnabled(true)
                }
                var netid = wifiManager.addNetwork(wifiConfiguration)
                wifiManager.disconnect()
                wifiManager.enableNetwork(netid, true)
                wifiManager.reconnect()
                result.success(true)
                return true
            } catch (e: Exception) {
                e.printStackTrace()
                result.success(false)
                return false
            }
        }
    }
}
```
put this in $your-project\android\app\src\main\kotlin\com\example\test\MainActivity.kt

```
import 'package:flutter/services.dart';

const MethodChannel _channel = MethodChannel('test/wifi');

Future<bool> initializeWifi(String ssid, String password) async {
  final bool result = await _channel.invokeMethod<bool>(
        'initializeWifi',
        <String, String>{'ssid': ssid, 'password': password},
      ) ??
      false;
  return result;
}
```
and put this in $your-project\lib\wifi_tool.dart


Now import the second file in your test and use initializeWifi method and check if it works or not.

**Comment by h1376h** [comment]
> > > Thanks, I tested with Android 10, 11 and 12. It works slower in Android 10 but works. In Android 11 and Android 12 it works and switches WiFi but it does not allow to use TCP Socket connection - IOT WiFi which does not have internet. Socket can not connect to IP port, seems like the problem is the OS detects that the WiFi does not have internet, it blocks all transport thru it. I reported the issue to Google but still no solution - https://issuetracker.google.com/issues/238443303
> > 
> > 
> > You mentioned that you checked wifi IoT package with "withInternet: false" parameter (and with additional WiFiForIoTPlugin.forceWifiUsage(true)), have you tried it with "withInternet: true"?
> > And is there any reason for not using the WifiSuggestion API?
> > The implemtion of WifiSuggestion (the one that it calls when using internet: true) in the package you mentioned has some problems as well, I may have a better idea providing a dart code for you to test, if you could explain what are you expecting to happen.
> > Are you trying to make the phone auto-connect to a wifi? Could the connection be peer to peer? If not, did you test both of the available APIs? (WifiNetworkSpecifier and WifiSuggestion)
> > Thanks for the response.
> 
> 1. Yes, I tried like "withInternet: true" as well.
> 2. No special reason - I did not find any Flutter library implementing that one. Which pub.dev package implement that API? Or should I implement it myself?
> 3. It would be very helpful if you can help. This is all what I need:
> 
> * Joining to a WiFi with given SSID and password (Connected WiFi does not have internet and never will - It is a way similar to Bluetooth to connect, commission, configure device thru WiFi connection)
> * Send byte data to that IOT device thru Flutter socket - something like: Socket.connect("ipHere", portNumberHere)

The only pub.dev package that uses WifiSuggestion API that I'm aware of is wifi_iot (the one you are already testing),
check if provided codes work for you and if they do, you need to implement it yourself.

**Comment by elmar001** [comment]
Thanks heaps man. I'll check it

**Comment by CadisRaziel** [comment]
@h1376h Thanks for answering the questions, we haven't had time lately because of a project on startup

**Comment by chenrilima** [comment]
thank you guys!
