### ISSUE TITLE
NEHotspotConfigurationHelper failed to communicate to helper server.  IOS

### ISSUE THREAD

**Issue by zhangyibo007** [CadisRaziel/plugin_wifi_connect#164]
Failed to send a 9 message to nehelper: <dictionary: 0x202164910> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x202164aa8> { length = 18, contents = "Connection invalid" }
}
NEHotspotConfigurationHelper failed to communicate to helper server.

**Comment by chenrilima** [comment]
can you tell us more details? for example, what you was doing to got this error ...
