### ISSUE TITLE
I have tested this package, I got an error

### ISSUE THREAD

**Issue by ferns-it** [CadisRaziel/plugin_wifi_connect#19]
I have tested your package with example app. But the app is showing<unknown ssid>. I already added all required permissions still it is showing like that  
![Screenshot_20220805-190714](https://user-images.githubusercontent.com/95687786/183089040-2cc00473-3f16-4244-bcb5-fe17ed77439d.png)

**Comment by h1376h** [comment]
Is your device's location on?

You can also add these lines to `yourproject\android\app\src\main`:

```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

and also use permission handler, after adding it to your pubspec.yaml by importing:

`import 'package:permission_handler/permission_handler.dart';`

and then get your ssid in a condition like this:

```
if (await Permission.location.request().isGranted) {
    // getting ssid
}
```


You need your device's location to be on and also a location access in your app for working with current ssid name, even if you want to use other packages.

**Comment by chenrilima** [comment]
> Is your device's location on? And does your example application have access to location?
> 
> **You need your device's location to be on and also a location access in your app for working with current ssid name, even when testing other packages.**
> 
> For better user experience, you can also add these lines to `AndroidManifest.xml`, located in `yourproject\android\app\src\main`:
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
> ```
> 
> and then use permission handler (after adding it to your pubspec.yaml)
> 
> `import 'package:permission_handler/permission_handler.dart';`
> 
> after importing it, you could get ssid in a condition like this:
> 
> ```
> if (await Permission.location.request().isGranted) {
>     // getting ssid
> }
> ```

nice! in android, have to do it.
