### ISSUE TITLE
Missing implementations on Android side.

### ISSUE THREAD

**Issue by ipatavatsizz** [CadisRaziel/plugin_wifi_connect#71]
Some methods on the plugin side throw errors because they are not implemented in Android, such as **activate wifi, isEnabled**.
Except for these methods, **disconnect, getSSID, connect, prefixConnect, secureConnect, and securePrefixConnect**, others are not implemented as mentioned above.

Also, I am getting gradle errors, current kotlin version is 1.7.10, what should I do?

```
What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':plugin_wifi_connect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 4s
```

**This needs to be fixed, please.**

**Comment by chenrilima** [comment]
Hi, we need to check this, because we use this package only for iOS, so we have no idea that android has some problems.

thanks for repporting us.

**Comment by lukasz-bialek** [comment]
The package configuration for latest flutter is OK. 
The only issue I see updated is:

 `compileSdkVersion 33
  minSdkVersion 19
`

Seems the lib was build with older kotlin version, or some bugs in build tools. 

I would also suggest building the plugin with updated pubspec.yaml:

`environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0`

**Comment by CadisRaziel** [comment]
@lukasz-bialek thanks for the support, this year 2023 I didn't have time to fix the problems in the package due to work, but now in 2024 I'll pay more attention
