### ISSUE TITLE
Build failed with Gradle version mismatch

### ISSUE THREAD

**Issue by ramanraja** [CadisRaziel/plugin_wifi_connect#77]
I got the following exception while trying to build your example application:
`https://pub.dev/packages/plugin_wifi_connect/example`

FAILURE: Build failed with an exception.
* What went wrong:
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':plugin_wifi_connect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

Build tool: Visual Studio Code 1.81.1
Target: Pixel Android emulator API level 34

**Comment by JooYoo** [comment]
Same here

**Comment by GiuseppeCrBrandi** [comment]
Same here. My solution was to migrate to a better library

**Comment by ramanraja** [comment]
" My solution was to migrate to a better library" - can you please name a library that works? Thank you.

**Comment by GiuseppeCrBrandi** [comment]
> " My solution was to migrate to a better library" - can you please name a library that works? Thank you.

Wifi_iot works wonderful

**Comment by integraodessa** [comment]
> > " My solution was to migrate to a better library" - can you please name a library that works? Thank you.
> 
> Wifi_iot works wonderful

Android 12 API 35 nothing works!

**Comment by CadisRaziel** [comment]
Hello everyone, in 2023 I had very little time to support the package, in 2024 I will pay more attention because I also use it in my project, thank you for your understanding and sorry for the delay

**Comment by ramanraja** [comment]
@CadisRaziel,
My IoT use case needs to switch between Wi-Fi networks, twice, without user intervention. Something like changing tires while the car is running! There seems to be no other viable solution for this as of today. 
Just wanted you to know that you have created a very unique and useful tool, and thank you.

**Comment by fabioselau077** [comment]
same

**Comment by alexobviously** [comment]
@CadisRaziel could you at least merge the dependabot PRs that you have pending and publish a patch release? I think this alone would solve the problem.

This is a fairly big problem now since Flutter 3.19.0 deprecates the old gradle buildscript style and effectively forces us to upgrade, so it would be much appreciated if you could spare a little time to do that!

**Comment by chenrilima** [comment]
> @CadisRaziel could you at least merge the dependabot PRs that you have pending and publish a patch release? I think this alone would solve the problem.
> 
> This is a fairly big problem now since Flutter 3.19.0 deprecates the old gradle buildscript style and effectively forces us to upgrade, so it would be much appreciated if you could spare a little time to do that!

Yes, sorry for late.
i've just done.
