### ISSUE TITLE
Android error: Could not get unknown property 'flutter' for extension 'android' of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by JooYoo** [CadisRaziel/plugin_wifi_connect#86]
Hey guys,

thanks for creating this plugin.
iOS works fine. But when I run on Android. I got the following error.
```
A problem occurred evaluating project ':plugin_wifi_connect'. > Could not get unknown property 'flutter' for extension 'android' of type com.android.build.gradle.LibraryExtension.
```
Here is my environment:
- Flutter 3.10.6
- Android SDK version 33.0.1

**Comment by CadisRaziel** [comment]
Thanks, I didn't have time to give support during the year due to work, but in 2024 I'll pay more attention to the package, thanks for reporting the error

**Comment by chenrilima** [comment]
> Hey guys,
> 
> thanks for creating this plugin. iOS works fine. But when I run on Android. I got the following error.
> 
> ```
> A problem occurred evaluating project ':plugin_wifi_connect'. > Could not get unknown property 'flutter' for extension 'android' of type com.android.build.gradle.LibraryExtension.
> ```
> 
> Here is my environment:
> 
> * Flutter 3.10.6
> * Android SDK version 33.0.1

how about today, dou yahe the same problem?

**Comment by chenrilima** [comment]
we have not anwser, so its closing this issue.
